
service: hackstheway


provider:
  name: aws
  runtime: java8
  timeout: 30
  environment:
    router_host: ${ssm:LEGACY_ROUTER_HOST}
    router_port: '80'
    bucket_name: ${ssm:HACK_BUCKET_NAME}
  iamRoleStatements:
     - Effect: "Allow"
       Action:
        - "s3:*"
       Resource: "*"

package:
  artifact: target/hackstheway-dev.jar

functions:
  hello:
    handler: com.himarley.hackathon.Handler
    events:
      - http:
          path: hackstheway/
          method: post


